### ISSUE TITLE
React v16 的关于 propTypes 的小坑

### ISSUE THREAD

**Issue by ChenHanZhang** [huzidaha/react-naive-book-examples#8]
这个教程已经两年多了，现在的React版本中，PropTypes独立出一个模块，旧代码中如果不改变引入方式将会报错。建议后来的读者可以参考一下：
[ReactJS “TypeError: Cannot read property 'array' of undefined”
](https://stackoverflow.com/questions/46722788/reactjs-typeerror-cannot-read-property-array-of-undefined)

**Comment by macc6579** [comment]
哈哈是的，我也遇见了这个问题
